# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"

  node:
    image: node:lts
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_started
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    command: "npm start"
