# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"
    networks:
      - backend

  api:
    image: node:slim
    restart: "always"
    ports:
      - "3333:3333"
    working_dir: "/home/node/app"
    volumes:
      - ./:/home/node/app
    command: "npm run start"
    depends_on:
      db:
        condition: service_started
    networks:
      - backend

networks:
  backend:
    driver: "bridge"