### POST videos
POST {{base_url}}/videos
Content-Type: application/json

{
  "title": "Video 2",
  "description": "Descrição do vídeo 2",
  "duration": 180
}

### GET videos
GET {{base_url}}/videos

###PUT videos
PUT {{base_url}}/videos/clman0k340000r7a2f5u1yk0r
Content-Type: application/json

{
  "title": "Video 3",
  "description": "Descrição do vídeo 3",
  "duration": 180
}

###DELETE videos
DELETE {{base_url}}/videos/clman0k340000r7a2f5u1yk0r